### Rest Cache
GET http://localhost:8000/api/v1/reset

### Check Train Status
GET http://localhost:8000/api/v1/train/status

### Advanced Writer Verification
POST http://localhost:8000/api/v1/predict/advanced-writer-verification
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.png"
Content-Type: text/plain

< ./manual_wv/test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Train Advanced Writer Verification Model
POST http://localhost:8000/api/v1/train
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file1"; filename="sample1.png"
Content-Type: image/png

< ./manual_wv/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file2"; filename="sample2.png"
Content-Type: image/png

< ./manual_wv/sample2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file3"; filename="sample3.png"
Content-Type: image/png

< ./manual_wv/sample3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Automatic Writer Verification
POST http://localhost:8000/api/v1/predict/automatic-writer-verification
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0g

------WebKitFormBoundary7MA4YWxkTrZu0g
Content-Disposition: form-data; name="file1"; filename="sample1.png"
Content-Type: image/png

< ./automatic_wv/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2"; filename="sample2.png"
Content-Type: image/png

< ./automatic_wv/sample2.png
------WebKitFormBoundary7MA4YWxkTrZu0g--

###
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
Content-Type: application/json
X-goog-api-key: {{$dotenv GEMINI_API}}

{
  "contents": [
    {
      "parts": [
        {
          "text": "Can you explain the difference between CNN and RNN in deep learning?"
        }
      ]
    }
  ]
}

