### Rest Cache
GET http://localhost:8000/api/v1/reset

### Check Train Status
GET http://localhost:8000/api/v1/train/status

### Personalized Writer Verification - Create Task
POST http://localhost:8000/api/v1/predict/personalized-writer-verification/create
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.png"
Content-Type: image/png

< ./manual_wv/test.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Personalized Writer Verification - Create Explanations
POST http://localhost:8000/api/v1/predict/personalized-writer-verification/explain
Content-Type: application/json

{
  "task_id": "hoYXUJaGwLM"
}

### Personalized Writer Verification - Create Interpretations
POST http://localhost:8000/api/v1/predict/personalized-writer-verification/interpret
Content-Type: application/json

{
  "task_id": "hoYXUJaGwLM"
}


### Train Advanced Writer Verification Model
POST http://localhost:8000/api/v1/train
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file1"; filename="sample1.png"
Content-Type: image/png

< ./manual_wv/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file2"; filename="sample2.png"
Content-Type: image/png

< ./manual_wv/sample2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file3"; filename="sample3.png"
Content-Type: image/png

< ./manual_wv/sample3.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Automatic Writer Verification
POST http://localhost:8000/api/v1/predict/automatic-writer-verification
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0g

------WebKitFormBoundary7MA4YWxkTrZu0g
Content-Disposition: form-data; name="file1"; filename="sample1.png"
Content-Type: image/png

< ./automatic_wv/sample1.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2"; filename="sample2.png"
Content-Type: image/png

< ./automatic_wv/sample2.png
------WebKitFormBoundary7MA4YWxkTrZu0g--

### Pairwise Automatic Writer Verification
POST http://localhost:8000/api/v1/predict/pairwise-writer-verification
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0g

------WebKitFormBoundary7MA4YWxkTrZu0g
Content-Disposition: form-data; name="file1_normal"; filename="file1_normal.png"
Content-Type: image/png

< ./automatic_wv/file1_normal.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file1_fast"; filename="file1_fast.png"
Content-Type: image/png

< ./automatic_wv/file1_fast.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2_normal"; filename="file2_normal.png"
Content-Type: image/png

< ./automatic_wv/file2_normal.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2_fast"; filename="file2_fast.png"
Content-Type: image/png

< ./automatic_wv/file2_fast.png
------WebKitFormBoundary7MA4YWxkTrZu0g--

### Pairwise Automatic Writer Verification
POST http://localhost:8000/api/v1/predict/pairwise-writer-verification
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0g

------WebKitFormBoundary7MA4YWxkTrZu0g
Content-Disposition: form-data; name="file1_normal"; filename="file1_normal.png"
Content-Type: image/png

< ./automatic_wv/file1_normal.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file1_fast"; filename="file1_fast.png"
Content-Type: image/png

< ./automatic_wv/file1_fast.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2_normal"; filename="file2_normal.png"
Content-Type: image/png

< ./automatic_wv/file2_normal.png
------WebKitFormBoundary7MA4YWxkTrZu0g

Content-Disposition: form-data; name="file2_fast"; filename="file2_fast.png"
Content-Type: image/png

< ./automatic_wv/file2_fast.png
------WebKitFormBoundary7MA4YWxkTrZu0g--



